# -*- coding: utf-8 -*-
"""HF-weights-download.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uf_UssZuyY0x1Bc5uSkOEIwEZhR-IgAU

### Step 1: Mount Google Drive

Mount your Drive to serve as the destination directory for the downloaded models.
"""

from google.colab import drive
drive.mount('/content/drive')

MODEL_ROOT = "/content/drive/MyDrive/hf_models"
!mkdir -p "$MODEL_ROOT"

print("Models will be stored in:", MODEL_ROOT)

"""### Step 2: Install Hugging Face Hub"""

!pip -q install -U huggingface_hub

"""### Authenticate with Hugging Face Hub (Optional but recommended)

Make sure you have added your token named `HF_TOKEN` in the Secrets (🔑) tab on the left panel.
"""

import os
from google.colab import userdata
from huggingface_hub import login

try:
    # Retrieve token from Colab secrets (🔑 tab) or env — never hardcode it.
    hf_token = userdata.get("HF_TOKEN") if "userdata" in dir() else os.environ.get("HF_TOKEN")
    login(token=hf_token)
    print("Successfully authenticated with Hugging Face!")
except Exception as e:
    print("Could not authenticate using HF_TOKEN from Colab secrets. Proceeding unauthenticated.")
    print("Error details:", e)

"""### Step 3: Check Actual Sizes of the Repositories

Let's check the size of each repository on Hugging Face before starting the downloads.
"""

from huggingface_hub import HfApi

api = HfApi()

for repo in [
    "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4",
    "nvidia/Qwen3.6-35B-A3B-NVFP4",
    "nvidia/GLM-5.2-NVFP4",
]:
    try:
        files = api.list_repo_tree(repo_id=repo, recursive=True)
        total = sum(f.size for f in files if hasattr(f, "size") and f.size)
        print(f"{repo:50s} {total / 1024**3:.2f} GB")
    except Exception as e:
        print(f"Could not fetch size for {repo}: {e}")

"""### Step 4: Individual Downloads

We download the models individually to keep things organized. If one model fails or Colab disconnects, you can rerun that specific cell safely with `resume_download=True`.

#### Download Nemotron
"""

from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4",
    local_dir="/content/drive/MyDrive/hf_models/nemotron-3-super-120b-a12b-nvfp4",
    local_dir_use_symlinks=False,
    resume_download=True,
)



"""#### Download Qwen3.6"""

from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="nvidia/Qwen3.6-35B-A3B-NVFP4",
    local_dir="/content/drive/MyDrive/hf_models/qwen3.6-35b-a3b-nvfp4",
    local_dir_use_symlinks=False,
    resume_download=True,
)

"""#### Download GLM-5.2"""

from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="nvidia/GLM-5.2-NVFP4",
    local_dir="/content/drive/MyDrive/hf_models/glm-5.2-nvfp4",
    local_dir_use_symlinks=False,
    resume_download=True,
)

"""### Step 5: Verify Storage

Check the sizes of your downloaded directories and current Google Drive disk space usage.
"""

!du -sh /content/drive/MyDrive/hf_models/*

!df -h /content/drive

"""### Step 6: Generate Remote Machine Download Script (using `gdown`)

Run the cell below to identify the folder ID of your shared `hf_models` folder on Google Drive and output the ready-to-use commands for your remote machine.
"""

import os
from google.colab import drive

# Source model directory
SOURCE_ROOT = "/content/drive/MyDrive/hf_models"
ARCHIVE_ROOT = "/content/drive/MyDrive/hf_models_zipped"

!mkdir -p "{ARCHIVE_ROOT}"

print("=== PREPARATION STEPS (Run on Colab) ===")
print("To ensure reliable downloading on the remote GB10 machine, we will package each model directory into a single tar archive:")

models = ["nemotron-3-super-120b-a12b-nvfp4", "qwen3.6-35b-a3b-nvfp4", "glm-5.2-nvfp4"]

for model in models:
    source_path = os.path.join(SOURCE_ROOT, model)
    archive_path = os.path.join(ARCHIVE_ROOT, f"{model}.tar")

    if os.path.exists(source_path):
        print(f"\nTo archive {model}, run this command in a new cell:")
        print(f"!tar -cf {archive_path} -C {SOURCE_ROOT} {model}")
    else:
        print(f"\n[Warning] {model} directory not found at {source_path}. Please download it first.")

print("\n=== REMOTE GB10 DOWNLOAD STEPS ===")
print("Once the .tar archives are created in your Drive, share each .tar file as 'Anyone with the link can view' and grab their File IDs.")
print("Then, run these commands on your remote GB10 machine:")
print("""
# 1. Install gdown
pip install gdown

# 2. Download and extract each model archive securely
# Replace <FILE_ID> with the actual shared file ID of each .tar file
gdown 'https://drive.google.com/uc?id=<NEMOTRON_FILE_ID>' -O nemotron.tar
tar -xf nemotron.tar -C /nvme/

gdown 'https://drive.google.com/uc?id=<QWEN_FILE_ID>' -O qwen.tar
tar -xf qwen.tar -C /nvme/

gdown 'https://drive.google.com/uc?id=<GLM_FILE_ID>' -O glm.tar
tar -xf glm.tar -C /nvme/
""")

"""### Step 6b: Create the Model Tar Archives on Google Drive

Run this cell to package the downloaded model folders into `.tar` files. This step will take some time depending on Google Drive disk writing speeds because the models are very large (especially GLM-5.2).
"""

import os

SOURCE_ROOT = "/content/drive/MyDrive/hf_models"
ARCHIVE_ROOT = "/content/drive/MyDrive/hf_models_zipped"

# Create the target directory if it doesn't exist
!mkdir -p "{ARCHIVE_ROOT}"

print("Starting archiving process for Nemotron...")

nemotron_path = f"{SOURCE_ROOT}/nemotron-3-super-120b-a12b-nvfp4"
nemotron_archive = f"{ARCHIVE_ROOT}/nemotron-3-super-120b-a12b-nvfp4.tar"

if os.path.exists(nemotron_path):
    print("\nArchiving Nemotron (this may take several minutes)...")
    !tar -cf {nemotron_archive} -C {SOURCE_ROOT} nemotron-3-super-120b-a12b-nvfp4
    print("Nemotron archiving complete!")
else:
    print(f"[Error] Nemotron directory not found at {nemotron_path}.")

"""### Step 7: Get Google Drive File IDs for the Model Archives

Execute the cell below to fetch the unique File IDs for the tar archives. Note: Make sure you run the archiving commands in cell `e11cb0b0` first so the `.tar` files exist in your Drive.
"""

from google.colab import auth
from googleapiclient.discovery import build

# Authenticate to access the Drive API metadata
auth.authenticate_user()
drive_service = build('drive', 'v3')

def get_gdrive_file_ids(folder_name="hf_models_zipped"):
    # Find the folder
    query = f"name = '{folder_name}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false"
    results = drive_service.files().list(q=query, fields="files(id, name)").execute()
    items = results.get('files', [])

    if not items:
        print(f"Could not find the folder '{folder_name}' in your Google Drive.")
        print("Please ensure you ran the archiving step in the previous cell to create it.")
        return

    folder_id = items[0]['id']

    # List all tar files in this folder
    query = f"'{folder_id}' in parents and trashed = false"
    results = drive_service.files().list(q=query, fields="files(id, name)").execute()
    files = results.get('files', [])

    print("=== YOUR MODEL FILE IDS ===\n")
    if not files:
        print("No archived files found in 'hf_models_zipped' yet.")
    for f in files:
        print(f"File: {f['name']}")
        print(f"ID:   {f['id']}")
        print(f"gdown Command:")
        print(f"gdown 'https://drive.google.com/uc?id={f['id']}' -O {f['name']}\n")

get_gdrive_file_ids()